IT_Company_Task_Manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("manager.urls", namespace="manager")),
                  path("registration/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path

from manager.views import (
    index,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView, toggle_assign_to_task
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        'tasks/<int:pk>/toggle/',
        toggle_assign_to_task,
        name='toggle_assign_to_task'
    ),
]

app_name = "manager"

manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Position(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True, blank=True, related_name='workers')

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Task(models.Model):
    class Priorities(models.TextChoices):
        LOW = "low", "Low"
        MEDIUM = "medium", "Medium"
        HIGH = "high", "High"
        URGENT = "urgent", "Urgent"

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=Priorities.choices)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE, related_name="tasks")
    assignees = models.ManyToManyField(Worker, related_name="tasks")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return self.name

manager/forms.py
from django import forms

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from manager.models import Position, Worker, Task


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = "__all__"


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position",
        )


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["username", "first_name", "last_name", "email", "position"]


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    deadline = forms.DateField(
        widget=forms.SelectDateWidget(
            empty_label=("Choose Year", "Choose Month", "Choose Day"),
        )
    )

    class Meta:
        model = Task
        fields = "__all__"


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )

manager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from manager.forms import (
    PositionForm,
    TaskForm,
    WorkerCreationForm,
    WorkerUpdateForm,
    TaskTypeSearchForm,
    PositionSearchForm,
    WorkerSearchForm,
    TaskSearchForm
)
from manager.models import TaskType, Position, Task, Worker


def index(request):
    """View function for the home page of the site"""
    num_workers = get_user_model().objects.count()
    num_positions = Position.objects.count()
    num_task_types = TaskType.objects.count()
    context = {
        "num_workers": num_workers,
        "num_positions": num_positions,
        "num_task_types": num_task_types,
    }
    return render(request, "manager/index.html", context=context)


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_type_list"
    template_name = "manager/task_type_list.html"
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = TaskType.objects.prefetch_related("tasks")
        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    template_name = 'manager/task_type_form.html'
    success_url = reverse_lazy("manager:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    template_name = 'manager/task_type_form.html'
    success_url = reverse_lazy("manager:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = 'manager/task_type_confirm_delete.html'
    success_url = reverse_lazy("manager:task-type-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Position.objects.prefetch_related("workers")
        form = PositionSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("manager:position-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = get_user_model()
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = get_user_model().objects.prefetch_related("position")
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    queryset = get_user_model().objects.prefetch_related("tasks")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = get_user_model()
    form_class = WorkerCreationForm
    success_url = reverse_lazy("manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("manager:worker-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.all().prefetch_related("assignees")
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.prefetch_related("assignees")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("manager:task-list")


@login_required
def toggle_assign_to_task(request, pk):
    task = Task.objects.get(id=pk)
    worker = request.user
    if task.assignees.filter(id=worker.id).exists():
        task.assignees.remove(worker)
    else:
        task.assignees.add(worker)
    return HttpResponseRedirect(reverse_lazy("manager:task-detail", args=[pk]))

templates/manager/index.html
<!--
=========================================================
* Material Kit 2 - v3.0.0
=========================================================

* Product Page:  https://www.creative-tim.com/product/material-kit 
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/favicon.png">

  <title>
    IT Task Manager
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/material-kit.css?v=3.0.0" rel="stylesheet" />

</head>
<body class="presentation-page bg-gray-200">

  {% include 'includes/navigation.html' %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">IT Task Manager</h1>
            <p class="lead text-white mt-3">A convenient way to optimize the work of the IT department <br /></p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 z-index-2 border-radius-xl mt-n7 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" class="text-gradient text-primary"
                                                             countTo="{{ num_workers }}"></span>+</h1>
                <h5 class="mt-3">Workers:</h5>
                <p class="text-sm">You can easily create and assign new workers</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state2" class="text-gradient text-primary"
                                                             countTo="{{ num_positions }}"></span>+</h1>
                <h5 class="mt-3">Positions:</h5>
                <p class="text-sm">Manage all workers positions in one place</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state3" class="text-gradient text-primary"
                                                             countTo="{{ num_task_types }}"></span>+</h1>
                <h5 class="mt-3">Task Types:</h5>
                <p class="text-sm">Use current or create a new one in a second</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
    <!-- -------   END PRE-FOOTER 2 - simple social line w/ title & 3 buttons    -------- -->
  </div>

  <footer class="footer pt-5 mt-5 w-100">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Task Types</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-type-list' %}">Task Types List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-type-create' %}">Create Task Type</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Positions</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:position-list' %}">Position List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:position-create' %}">Create Position</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Workers</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:worker-list' %}">Worker List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:worker-create' %}">Create Worker</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Tasks</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-list' %}">Task List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-create' %}">Create Task</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-12 text-center">
                <div class="text-center">
                    <p class="text-dark my-4 text-sm font-weight-normal">
                        &copy; 2024. All rights reserved.
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>


  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>
</body>

</html>

templates/manager/position_list.html
{% extends 'layouts/base.html' %}

{% block title %} Manager {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="py-7">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
            
          <h3><a href="{% url 'manager:position-create' %}"
               class="btn bg-gradient-success w-auto me-2">Create position</a>Position List:
          </h3>
        </div>
        <div class="col-lg-4 offset-lg-3">
          {% include "includes/search_form.html" %}
        </div>
      </div>
      <div class="row">
        {% if position_list %}
          {% for position in position_list %}
            <div class="col-lg-3 col-sm-6 my-2">
              <div class="card card-plain card-blog bg-gradient-faded-white">
                <div class="card-body px-0 m-1 mx-3">
                  <h5 class="text-dark font-weight-bold">
                    {{ position.name }}
                  </h5>
                  {% if position.workers.all %}
                    <p class="mb-0"><i class="fas fa-user-friends me-1"></i>Work in this position:</p>
                    {% for worker in position.workers.all %}
                      <a class="py-2" href="{% url 'manager:worker-detail' pk=worker.id %}">
                        <u>{{ worker.get_full_name }}</u>{% if not forloop.last %}, {% endif %}</a>
                    {% endfor %}
                  {% else %}
                    <p>No one works in this position yet</p>
                  {% endif %}
                  <br>
                  <br>
                  <a class="btn bg-gradient-success mt-4 py-2 pe-4"
                     href="{% url 'manager:position-update' pk=position.id %}"
                  ><i class="fas fa-pen me-1"></i>Update</a>
                  <a class="btn bg-gradient-danger mt-4 py-2 pe-4"
                     href="{% url 'manager:position-delete' pk=position.id %}"
                  ><i class="fas fa-trash me-1"></i>Delete</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p>There are no positions yet</p>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/task_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Manager {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="py-7">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <h1>
            {{ task.name }}
              <h1>
            <a href="{% url 'manager:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
              Delete
            </a>
            <a href="{% url 'manager:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
              Update
            </a>
                  </h1>
          </h1>
          <p>Description: {{ task.description }}</p>
          <p>Priority: {{ task.get_priority_display }}</p>
          <p>Task Type: {{ task.task_type.name }}</p>
          <p>Deadline: {{ task.deadline }}</p>
          <p>Is Completed: {{ task.is_completed }}</p>
          
          <h1>Assignees</h1>
                  {% if task in user.tasks.all %}
            <a href="{% url 'manager:toggle_assign_to_task' pk=task.id %}" class="btn btn-danger link-to-page">
              Remove me from this task
            </a>
          {% else %}
            <a href="{% url 'manager:toggle_assign_to_task' pk=task.id %}" class="btn btn-success link-to-page">
              Assign me to this task
            </a>
          {% endif %}
          <hr>
          <ul>
            {% for worker in task.assignees.all %}
              <li>{{ worker.username }} ({{ worker.first_name }} {{ worker.last_name }})</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/manager/worker_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Manager {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="py-7">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <h1>
            <a href="{% url 'manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
              Delete
            </a>
            <a href="{% url 'manager:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">
              Update
            </a>
          </h1>

          <p><strong>First name:</strong> {{ worker.first_name }}</p>
          <p><strong>Last name:</strong> {{ worker.last_name }}</p>
          <p><strong>Position:</strong> {{ worker.position }}</p>
          <p><strong>Is staff:</strong> {{ worker.is_staff }}</p>

          <div class="ml-3">
            <h4>Tasks</h4>

            {% for task in worker.tasks.all %}
              <hr>
              <p><strong>Task Name:</strong> {{ task.name }}</p>
              <p><strong>Task Type:</strong> {{ task.task_type.name }}</p>
              <p class="text-muted"><strong>Id:</strong> {{ task.id }}</p>
            {% empty %}
              <p>No tasks assigned!</p>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/worker_list.html
{% extends 'layouts/base.html' %}

{% block title %} Manager {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% include "includes/navigation.html" %}
  <section class="py-7">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <h3>
            <a href="{% url 'manager:worker-create' %}" class="btn bg-gradient-success w-auto me-2">Create worker</a>
            Worker List:
          </h3>
        </div>
        <div class="col-lg-4 offset-lg-3">
          {% include "includes/search_form.html" %}
        </div>
      </div>
      <div class="row">
        {% if worker_list %}
          <table class="table">
            <tr>
              <th>Username</th>
              <th>First name</th>
              <th>Last name</th>
              <th>Position</th>
            </tr>
            {% for worker in worker_list %}
              <tr>
                <td>
                  <a href="{% url 'manager:worker-detail' pk=worker.id %}">{{ worker.username }} {% if user == worker %} (Me) {% endif %}</a>
                </td>
                <td>{{ worker.first_name }}</td>
                <td>{{ worker.last_name }}</td>
                <td>{{ worker.position }}</td>
              </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>No workers found.</p>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}