IT_Company_Task_Manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("manager.urls", namespace="manager")),
                  path("registration/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path

from manager.views import (
    index,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView, toggle_assign_to_task
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task_types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "task_types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        'tasks/<int:pk>/toggle/',
        toggle_assign_to_task,
        name='toggle_assign_to_task'
    ),
]

app_name = "manager"

templates/includes/footer.html
<footer class="footer pt-5 mt-5 w-100">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Task Types</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-type-list' %}">Task Types List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-type-create' %}">Create Task Type</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Positions</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:position-list' %}">Position List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:position-create' %}">Create Position</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Workers</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:worker-list' %}">Worker List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:worker-create' %}">Create Worker</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-6 col-6 mb-4 text-center">
                <div>
                    <h6 class="text-sm">Tasks</h6>
                    <ul class="flex-column ms-n3 nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-list' %}">Task List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'manager:task-create' %}">Create Task</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-12 text-center">
                <div class="text-center">
                    <p class="text-dark my-4 text-sm font-weight-normal">
                        &copy; 2024. All rights reserved.
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/navigation.html
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
            IT Task Manager
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ms-auto">

              <!-- Dropdown for Tasks -->
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuTasks" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">checklist</i>
                  Tasks
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuTasks">
                  <a href="{% url 'manager:task-list' %}" class="dropdown-item border-radius-md">
                    <span>All Tasks</span>
                  </a>
                  <a href="{% url 'manager:task-create' %}" class="dropdown-item border-radius-md">
                    <span>Create Task</span>
                  </a>
                </div>
              </li>

              <!-- Dropdown for Task Types -->
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuTaskTypes" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">category</i>
                  Task Types
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuTaskTypes">
                  <a href="{% url 'manager:task-type-list' %}" class="dropdown-item border-radius-md">
                    <span>All Task Types</span>
                  </a>
                  <a href="{% url 'manager:task-type-create' %}" class="dropdown-item border-radius-md">
                    <span>Create Task Type</span>
                  </a>
                </div>
              </li>

              <!-- Dropdown for Positions -->
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPositions" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">work</i>
                  Positions
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPositions">
                  <a href="{% url 'manager:position-list' %}" class="dropdown-item border-radius-md">
                    <span>All Positions</span>
                  </a>
                  <a href="{% url 'manager:position-create' %}" class="dropdown-item border-radius-md">
                    <span>Create Position</span>
                  </a>
                </div>
              </li>

              <!-- Dropdown for Worker -->
              <li class="nav-item dropdown dropdown-hover mx-2">
                <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuWorkers" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="material-icons opacity-6 me-2 text-md">people</i>
                  Worker
                  <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                </a>
                <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuWorkers">
                  <a href="{% url 'manager:worker-list' %}" class="dropdown-item border-radius-md">
                    <span>All Workers</span>
                  </a>
                  <a href="{% url 'manager:worker-create' %}" class="dropdown-item border-radius-md">
                    <span>Create Worker</span>
                  </a>
                </div>
              </li>

              {% if request.user.is_authenticated %}
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="btn bg-gradient-danger mb-0 me-1 mt-2 mt-md-0" type="submit" style="border: none; padding: 0.5rem 1rem;">
                      <i class="fa fa-sign-out me-1"></i>
                      <span class="text-sm font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</span>
                    </button>
                  </form>
                </li>
              {% else %}
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <button class="btn bg-gradient-success mb-0 me-1 mt-2 mt-md-0" type="submit" style="border: none; padding: 0.5rem 1rem;">
                      <span class="text-sm font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign IN">Login</span>
                    </button>
                  </form>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="row text-center py-2">
    <div class="col-auto mx-auto">
      <ul class="pagination pagination-primary">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link"
               href="?{% query_transform request page=page_obj.previous_page_number %}"
               aria-label="Previous">
              <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
            </a>
          </li>
        {% endif %}
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item active">
              <span class="page-link">{{ page_obj.number }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link"
                 href="?{% query_transform request page=page_num %}"
                 aria-label="Previous">
                <span>{{ page_num }}</span>
              </a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link"
               href="?{% query_transform request page=page_obj.next_page_number %}"
               aria-label="Next">
              <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/search_form.html
{% load crispy_forms_filters %}
{% load static %}
<div class="row justify-content-end">
  <form class="form-inline-search d-flex" action="" method="get">
    {% csrf_token %}
    <div class="form-control">
        {{ search_form|crispy }}
    </div>
    <button class="btn btn-outline-dark" id="search-btn" type="submit" value="submit">
      <i class="fa fa-search"></i>
    </button>
  </form>
</div>